package top.kutsko.googleauthconverter.model;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: OtpMigration.proto
// Protobuf Java Version: 4.30.2

public final class OtpMigration {
  private OtpMigration() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      OtpMigration.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code Algorithm}
   */
  public enum Algorithm
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ALGORITHM_TYPE_UNSPECIFIED = 0;</code>
     */
    ALGORITHM_TYPE_UNSPECIFIED(0),
    /**
     * <code>SHA1 = 1;</code>
     */
    SHA1(1),
    /**
     * <code>SHA256 = 2;</code>
     */
    SHA256(2),
    /**
     * <code>SHA512 = 3;</code>
     */
    SHA512(3),
    /**
     * <code>MD5 = 4;</code>
     */
    MD5(4),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        Algorithm.class.getName());
    }
    /**
     * <code>ALGORITHM_TYPE_UNSPECIFIED = 0;</code>
     */
    public static final int ALGORITHM_TYPE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>SHA1 = 1;</code>
     */
    public static final int SHA1_VALUE = 1;
    /**
     * <code>SHA256 = 2;</code>
     */
    public static final int SHA256_VALUE = 2;
    /**
     * <code>SHA512 = 3;</code>
     */
    public static final int SHA512_VALUE = 3;
    /**
     * <code>MD5 = 4;</code>
     */
    public static final int MD5_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Algorithm valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Algorithm forNumber(int value) {
      switch (value) {
        case 0: return ALGORITHM_TYPE_UNSPECIFIED;
        case 1: return SHA1;
        case 2: return SHA256;
        case 3: return SHA512;
        case 4: return MD5;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Algorithm>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Algorithm> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Algorithm>() {
            public Algorithm findValueByNumber(int number) {
              return Algorithm.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return OtpMigration.getDescriptor().getEnumTypes().get(0);
    }

    private static final Algorithm[] VALUES = values();

    public static Algorithm valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Algorithm(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Algorithm)
  }

  /**
   * Protobuf enum {@code DigitCount}
   */
  public enum DigitCount
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DIGIT_COUNT_UNSPECIFIED = 0;</code>
     */
    DIGIT_COUNT_UNSPECIFIED(0),
    /**
     * <code>SIX = 1;</code>
     */
    SIX(1),
    /**
     * <code>EIGHT = 2;</code>
     */
    EIGHT(2),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        DigitCount.class.getName());
    }
    /**
     * <code>DIGIT_COUNT_UNSPECIFIED = 0;</code>
     */
    public static final int DIGIT_COUNT_UNSPECIFIED_VALUE = 0;
    /**
     * <code>SIX = 1;</code>
     */
    public static final int SIX_VALUE = 1;
    /**
     * <code>EIGHT = 2;</code>
     */
    public static final int EIGHT_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static DigitCount valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DigitCount forNumber(int value) {
      switch (value) {
        case 0: return DIGIT_COUNT_UNSPECIFIED;
        case 1: return SIX;
        case 2: return EIGHT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DigitCount>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DigitCount> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DigitCount>() {
            public DigitCount findValueByNumber(int number) {
              return DigitCount.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return OtpMigration.getDescriptor().getEnumTypes().get(1);
    }

    private static final DigitCount[] VALUES = values();

    public static DigitCount valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DigitCount(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:DigitCount)
  }

  /**
   * Protobuf enum {@code OtpType}
   */
  public enum OtpType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OTP_TYPE_UNSPECIFIED = 0;</code>
     */
    OTP_TYPE_UNSPECIFIED(0),
    /**
     * <code>HOTP = 1;</code>
     */
    HOTP(1),
    /**
     * <code>TOTP = 2;</code>
     */
    TOTP(2),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        OtpType.class.getName());
    }
    /**
     * <code>OTP_TYPE_UNSPECIFIED = 0;</code>
     */
    public static final int OTP_TYPE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>HOTP = 1;</code>
     */
    public static final int HOTP_VALUE = 1;
    /**
     * <code>TOTP = 2;</code>
     */
    public static final int TOTP_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static OtpType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static OtpType forNumber(int value) {
      switch (value) {
        case 0: return OTP_TYPE_UNSPECIFIED;
        case 1: return HOTP;
        case 2: return TOTP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OtpType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OtpType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OtpType>() {
            public OtpType findValueByNumber(int number) {
              return OtpType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return OtpMigration.getDescriptor().getEnumTypes().get(2);
    }

    private static final OtpType[] VALUES = values();

    public static OtpType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OtpType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:OtpType)
  }

  public interface MigrationPayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MigrationPayload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .OtpParameters otp_parameters = 1;</code>
     */
    java.util.List<OtpParameters>
        getOtpParametersList();
    /**
     * <code>repeated .OtpParameters otp_parameters = 1;</code>
     */
    OtpParameters getOtpParameters(int index);
    /**
     * <code>repeated .OtpParameters otp_parameters = 1;</code>
     */
    int getOtpParametersCount();
    /**
     * <code>repeated .OtpParameters otp_parameters = 1;</code>
     */
    java.util.List<? extends OtpParametersOrBuilder>
        getOtpParametersOrBuilderList();
    /**
     * <code>repeated .OtpParameters otp_parameters = 1;</code>
     */
    OtpParametersOrBuilder getOtpParametersOrBuilder(
        int index);

    /**
     * <code>optional int32 version = 2;</code>
     * @return Whether the version field is set.
     */
    boolean hasVersion();
    /**
     * <code>optional int32 version = 2;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <code>optional int32 batch_size = 3;</code>
     * @return Whether the batchSize field is set.
     */
    boolean hasBatchSize();
    /**
     * <code>optional int32 batch_size = 3;</code>
     * @return The batchSize.
     */
    int getBatchSize();

    /**
     * <code>optional int32 batch_index = 4;</code>
     * @return Whether the batchIndex field is set.
     */
    boolean hasBatchIndex();
    /**
     * <code>optional int32 batch_index = 4;</code>
     * @return The batchIndex.
     */
    int getBatchIndex();

    /**
     * <code>optional int32 batch_id = 5;</code>
     * @return Whether the batchId field is set.
     */
    boolean hasBatchId();
    /**
     * <code>optional int32 batch_id = 5;</code>
     * @return The batchId.
     */
    int getBatchId();
  }
  /**
   * Protobuf type {@code MigrationPayload}
   */
  public static final class MigrationPayload extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MigrationPayload)
      MigrationPayloadOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        MigrationPayload.class.getName());
    }
    // Use MigrationPayload.newBuilder() to construct.
    private MigrationPayload(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MigrationPayload() {
      otpParameters_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OtpMigration.internal_static_MigrationPayload_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OtpMigration.internal_static_MigrationPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MigrationPayload.class, Builder.class);
    }

    private int bitField0_;
    public static final int OTP_PARAMETERS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<OtpParameters> otpParameters_;
    /**
     * <code>repeated .OtpParameters otp_parameters = 1;</code>
     */
    @Override
    public java.util.List<OtpParameters> getOtpParametersList() {
      return otpParameters_;
    }
    /**
     * <code>repeated .OtpParameters otp_parameters = 1;</code>
     */
    @Override
    public java.util.List<? extends OtpParametersOrBuilder>
        getOtpParametersOrBuilderList() {
      return otpParameters_;
    }
    /**
     * <code>repeated .OtpParameters otp_parameters = 1;</code>
     */
    @Override
    public int getOtpParametersCount() {
      return otpParameters_.size();
    }
    /**
     * <code>repeated .OtpParameters otp_parameters = 1;</code>
     */
    @Override
    public OtpParameters getOtpParameters(int index) {
      return otpParameters_.get(index);
    }
    /**
     * <code>repeated .OtpParameters otp_parameters = 1;</code>
     */
    @Override
    public OtpParametersOrBuilder getOtpParametersOrBuilder(
        int index) {
      return otpParameters_.get(index);
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private int version_ = 0;
    /**
     * <code>optional int32 version = 2;</code>
     * @return Whether the version field is set.
     */
    @Override
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 version = 2;</code>
     * @return The version.
     */
    @Override
    public int getVersion() {
      return version_;
    }

    public static final int BATCH_SIZE_FIELD_NUMBER = 3;
    private int batchSize_ = 0;
    /**
     * <code>optional int32 batch_size = 3;</code>
     * @return Whether the batchSize field is set.
     */
    @Override
    public boolean hasBatchSize() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 batch_size = 3;</code>
     * @return The batchSize.
     */
    @Override
    public int getBatchSize() {
      return batchSize_;
    }

    public static final int BATCH_INDEX_FIELD_NUMBER = 4;
    private int batchIndex_ = 0;
    /**
     * <code>optional int32 batch_index = 4;</code>
     * @return Whether the batchIndex field is set.
     */
    @Override
    public boolean hasBatchIndex() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 batch_index = 4;</code>
     * @return The batchIndex.
     */
    @Override
    public int getBatchIndex() {
      return batchIndex_;
    }

    public static final int BATCH_ID_FIELD_NUMBER = 5;
    private int batchId_ = 0;
    /**
     * <code>optional int32 batch_id = 5;</code>
     * @return Whether the batchId field is set.
     */
    @Override
    public boolean hasBatchId() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 batch_id = 5;</code>
     * @return The batchId.
     */
    @Override
    public int getBatchId() {
      return batchId_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < otpParameters_.size(); i++) {
        output.writeMessage(1, otpParameters_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(2, version_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(3, batchSize_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(4, batchIndex_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(5, batchId_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < otpParameters_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, otpParameters_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, version_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, batchSize_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, batchIndex_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, batchId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MigrationPayload)) {
        return super.equals(obj);
      }
      MigrationPayload other = (MigrationPayload) obj;

      if (!getOtpParametersList()
          .equals(other.getOtpParametersList())) return false;
      if (hasVersion() != other.hasVersion()) return false;
      if (hasVersion()) {
        if (getVersion()
            != other.getVersion()) return false;
      }
      if (hasBatchSize() != other.hasBatchSize()) return false;
      if (hasBatchSize()) {
        if (getBatchSize()
            != other.getBatchSize()) return false;
      }
      if (hasBatchIndex() != other.hasBatchIndex()) return false;
      if (hasBatchIndex()) {
        if (getBatchIndex()
            != other.getBatchIndex()) return false;
      }
      if (hasBatchId() != other.hasBatchId()) return false;
      if (hasBatchId()) {
        if (getBatchId()
            != other.getBatchId()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getOtpParametersCount() > 0) {
        hash = (37 * hash) + OTP_PARAMETERS_FIELD_NUMBER;
        hash = (53 * hash) + getOtpParametersList().hashCode();
      }
      if (hasVersion()) {
        hash = (37 * hash) + VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getVersion();
      }
      if (hasBatchSize()) {
        hash = (37 * hash) + BATCH_SIZE_FIELD_NUMBER;
        hash = (53 * hash) + getBatchSize();
      }
      if (hasBatchIndex()) {
        hash = (37 * hash) + BATCH_INDEX_FIELD_NUMBER;
        hash = (53 * hash) + getBatchIndex();
      }
      if (hasBatchId()) {
        hash = (37 * hash) + BATCH_ID_FIELD_NUMBER;
        hash = (53 * hash) + getBatchId();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MigrationPayload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MigrationPayload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MigrationPayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MigrationPayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MigrationPayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MigrationPayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MigrationPayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static MigrationPayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static MigrationPayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static MigrationPayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MigrationPayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static MigrationPayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MigrationPayload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MigrationPayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MigrationPayload)
        MigrationPayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return OtpMigration.internal_static_MigrationPayload_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OtpMigration.internal_static_MigrationPayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MigrationPayload.class, Builder.class);
      }

      // Construct using OtpMigration.MigrationPayload.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (otpParametersBuilder_ == null) {
          otpParameters_ = java.util.Collections.emptyList();
        } else {
          otpParameters_ = null;
          otpParametersBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        batchSize_ = 0;
        batchIndex_ = 0;
        batchId_ = 0;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return OtpMigration.internal_static_MigrationPayload_descriptor;
      }

      @Override
      public MigrationPayload getDefaultInstanceForType() {
        return MigrationPayload.getDefaultInstance();
      }

      @Override
      public MigrationPayload build() {
        MigrationPayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MigrationPayload buildPartial() {
        MigrationPayload result = new MigrationPayload(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(MigrationPayload result) {
        if (otpParametersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            otpParameters_ = java.util.Collections.unmodifiableList(otpParameters_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.otpParameters_ = otpParameters_;
        } else {
          result.otpParameters_ = otpParametersBuilder_.build();
        }
      }

      private void buildPartial0(MigrationPayload result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.version_ = version_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.batchSize_ = batchSize_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.batchIndex_ = batchIndex_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.batchId_ = batchId_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MigrationPayload) {
          return mergeFrom((MigrationPayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MigrationPayload other) {
        if (other == MigrationPayload.getDefaultInstance()) return this;
        if (otpParametersBuilder_ == null) {
          if (!other.otpParameters_.isEmpty()) {
            if (otpParameters_.isEmpty()) {
              otpParameters_ = other.otpParameters_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureOtpParametersIsMutable();
              otpParameters_.addAll(other.otpParameters_);
            }
            onChanged();
          }
        } else {
          if (!other.otpParameters_.isEmpty()) {
            if (otpParametersBuilder_.isEmpty()) {
              otpParametersBuilder_.dispose();
              otpParametersBuilder_ = null;
              otpParameters_ = other.otpParameters_;
              bitField0_ = (bitField0_ & ~0x00000001);
              otpParametersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetOtpParametersFieldBuilder() : null;
            } else {
              otpParametersBuilder_.addAllMessages(other.otpParameters_);
            }
          }
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasBatchSize()) {
          setBatchSize(other.getBatchSize());
        }
        if (other.hasBatchIndex()) {
          setBatchIndex(other.getBatchIndex());
        }
        if (other.hasBatchId()) {
          setBatchId(other.getBatchId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                OtpParameters m =
                    input.readMessage(
                        OtpParameters.parser(),
                        extensionRegistry);
                if (otpParametersBuilder_ == null) {
                  ensureOtpParametersIsMutable();
                  otpParameters_.add(m);
                } else {
                  otpParametersBuilder_.addMessage(m);
                }
                break;
              } // case 10
              case 16: {
                version_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                batchSize_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                batchIndex_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                batchId_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<OtpParameters> otpParameters_ =
        java.util.Collections.emptyList();
      private void ensureOtpParametersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          otpParameters_ = new java.util.ArrayList<OtpParameters>(otpParameters_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          OtpParameters, OtpParameters.Builder, OtpParametersOrBuilder> otpParametersBuilder_;

      /**
       * <code>repeated .OtpParameters otp_parameters = 1;</code>
       */
      public java.util.List<OtpParameters> getOtpParametersList() {
        if (otpParametersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(otpParameters_);
        } else {
          return otpParametersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .OtpParameters otp_parameters = 1;</code>
       */
      public int getOtpParametersCount() {
        if (otpParametersBuilder_ == null) {
          return otpParameters_.size();
        } else {
          return otpParametersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .OtpParameters otp_parameters = 1;</code>
       */
      public OtpParameters getOtpParameters(int index) {
        if (otpParametersBuilder_ == null) {
          return otpParameters_.get(index);
        } else {
          return otpParametersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .OtpParameters otp_parameters = 1;</code>
       */
      public Builder setOtpParameters(
          int index, OtpParameters value) {
        if (otpParametersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOtpParametersIsMutable();
          otpParameters_.set(index, value);
          onChanged();
        } else {
          otpParametersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .OtpParameters otp_parameters = 1;</code>
       */
      public Builder setOtpParameters(
          int index, OtpParameters.Builder builderForValue) {
        if (otpParametersBuilder_ == null) {
          ensureOtpParametersIsMutable();
          otpParameters_.set(index, builderForValue.build());
          onChanged();
        } else {
          otpParametersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OtpParameters otp_parameters = 1;</code>
       */
      public Builder addOtpParameters(OtpParameters value) {
        if (otpParametersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOtpParametersIsMutable();
          otpParameters_.add(value);
          onChanged();
        } else {
          otpParametersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .OtpParameters otp_parameters = 1;</code>
       */
      public Builder addOtpParameters(
          int index, OtpParameters value) {
        if (otpParametersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOtpParametersIsMutable();
          otpParameters_.add(index, value);
          onChanged();
        } else {
          otpParametersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .OtpParameters otp_parameters = 1;</code>
       */
      public Builder addOtpParameters(
          OtpParameters.Builder builderForValue) {
        if (otpParametersBuilder_ == null) {
          ensureOtpParametersIsMutable();
          otpParameters_.add(builderForValue.build());
          onChanged();
        } else {
          otpParametersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OtpParameters otp_parameters = 1;</code>
       */
      public Builder addOtpParameters(
          int index, OtpParameters.Builder builderForValue) {
        if (otpParametersBuilder_ == null) {
          ensureOtpParametersIsMutable();
          otpParameters_.add(index, builderForValue.build());
          onChanged();
        } else {
          otpParametersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OtpParameters otp_parameters = 1;</code>
       */
      public Builder addAllOtpParameters(
          Iterable<? extends OtpParameters> values) {
        if (otpParametersBuilder_ == null) {
          ensureOtpParametersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, otpParameters_);
          onChanged();
        } else {
          otpParametersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .OtpParameters otp_parameters = 1;</code>
       */
      public Builder clearOtpParameters() {
        if (otpParametersBuilder_ == null) {
          otpParameters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          otpParametersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .OtpParameters otp_parameters = 1;</code>
       */
      public Builder removeOtpParameters(int index) {
        if (otpParametersBuilder_ == null) {
          ensureOtpParametersIsMutable();
          otpParameters_.remove(index);
          onChanged();
        } else {
          otpParametersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .OtpParameters otp_parameters = 1;</code>
       */
      public OtpParameters.Builder getOtpParametersBuilder(
          int index) {
        return internalGetOtpParametersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .OtpParameters otp_parameters = 1;</code>
       */
      public OtpParametersOrBuilder getOtpParametersOrBuilder(
          int index) {
        if (otpParametersBuilder_ == null) {
          return otpParameters_.get(index);  } else {
          return otpParametersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .OtpParameters otp_parameters = 1;</code>
       */
      public java.util.List<? extends OtpParametersOrBuilder>
           getOtpParametersOrBuilderList() {
        if (otpParametersBuilder_ != null) {
          return otpParametersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(otpParameters_);
        }
      }
      /**
       * <code>repeated .OtpParameters otp_parameters = 1;</code>
       */
      public OtpParameters.Builder addOtpParametersBuilder() {
        return internalGetOtpParametersFieldBuilder().addBuilder(
            OtpParameters.getDefaultInstance());
      }
      /**
       * <code>repeated .OtpParameters otp_parameters = 1;</code>
       */
      public OtpParameters.Builder addOtpParametersBuilder(
          int index) {
        return internalGetOtpParametersFieldBuilder().addBuilder(
            index, OtpParameters.getDefaultInstance());
      }
      /**
       * <code>repeated .OtpParameters otp_parameters = 1;</code>
       */
      public java.util.List<OtpParameters.Builder>
           getOtpParametersBuilderList() {
        return internalGetOtpParametersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          OtpParameters, OtpParameters.Builder, OtpParametersOrBuilder>
          internalGetOtpParametersFieldBuilder() {
        if (otpParametersBuilder_ == null) {
          otpParametersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              OtpParameters, OtpParameters.Builder, OtpParametersOrBuilder>(
                  otpParameters_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          otpParameters_ = null;
        }
        return otpParametersBuilder_;
      }

      private int version_ ;
      /**
       * <code>optional int32 version = 2;</code>
       * @return Whether the version field is set.
       */
      @Override
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 version = 2;</code>
       * @return The version.
       */
      @Override
      public int getVersion() {
        return version_;
      }
      /**
       * <code>optional int32 version = 2;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {

        version_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 version = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        version_ = 0;
        onChanged();
        return this;
      }

      private int batchSize_ ;
      /**
       * <code>optional int32 batch_size = 3;</code>
       * @return Whether the batchSize field is set.
       */
      @Override
      public boolean hasBatchSize() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 batch_size = 3;</code>
       * @return The batchSize.
       */
      @Override
      public int getBatchSize() {
        return batchSize_;
      }
      /**
       * <code>optional int32 batch_size = 3;</code>
       * @param value The batchSize to set.
       * @return This builder for chaining.
       */
      public Builder setBatchSize(int value) {

        batchSize_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 batch_size = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBatchSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        batchSize_ = 0;
        onChanged();
        return this;
      }

      private int batchIndex_ ;
      /**
       * <code>optional int32 batch_index = 4;</code>
       * @return Whether the batchIndex field is set.
       */
      @Override
      public boolean hasBatchIndex() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 batch_index = 4;</code>
       * @return The batchIndex.
       */
      @Override
      public int getBatchIndex() {
        return batchIndex_;
      }
      /**
       * <code>optional int32 batch_index = 4;</code>
       * @param value The batchIndex to set.
       * @return This builder for chaining.
       */
      public Builder setBatchIndex(int value) {

        batchIndex_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 batch_index = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBatchIndex() {
        bitField0_ = (bitField0_ & ~0x00000008);
        batchIndex_ = 0;
        onChanged();
        return this;
      }

      private int batchId_ ;
      /**
       * <code>optional int32 batch_id = 5;</code>
       * @return Whether the batchId field is set.
       */
      @Override
      public boolean hasBatchId() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional int32 batch_id = 5;</code>
       * @return The batchId.
       */
      @Override
      public int getBatchId() {
        return batchId_;
      }
      /**
       * <code>optional int32 batch_id = 5;</code>
       * @param value The batchId to set.
       * @return This builder for chaining.
       */
      public Builder setBatchId(int value) {

        batchId_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 batch_id = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBatchId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        batchId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MigrationPayload)
    }

    // @@protoc_insertion_point(class_scope:MigrationPayload)
    private static final MigrationPayload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MigrationPayload();
    }

    public static MigrationPayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MigrationPayload>
        PARSER = new com.google.protobuf.AbstractParser<MigrationPayload>() {
      @Override
      public MigrationPayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MigrationPayload> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MigrationPayload> getParserForType() {
      return PARSER;
    }

    @Override
    public MigrationPayload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OtpParametersOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OtpParameters)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes secret = 1;</code>
     * @return Whether the secret field is set.
     */
    boolean hasSecret();
    /**
     * <code>optional bytes secret = 1;</code>
     * @return The secret.
     */
    com.google.protobuf.ByteString getSecret();

    /**
     * <code>optional string name = 2;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>optional string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string issuer = 3;</code>
     * @return Whether the issuer field is set.
     */
    boolean hasIssuer();
    /**
     * <code>optional string issuer = 3;</code>
     * @return The issuer.
     */
    String getIssuer();
    /**
     * <code>optional string issuer = 3;</code>
     * @return The bytes for issuer.
     */
    com.google.protobuf.ByteString
        getIssuerBytes();

    /**
     * <code>optional .Algorithm algorithm = 4;</code>
     * @return Whether the algorithm field is set.
     */
    boolean hasAlgorithm();
    /**
     * <code>optional .Algorithm algorithm = 4;</code>
     * @return The algorithm.
     */
    Algorithm getAlgorithm();

    /**
     * <code>optional .DigitCount digits = 5;</code>
     * @return Whether the digits field is set.
     */
    boolean hasDigits();
    /**
     * <code>optional .DigitCount digits = 5;</code>
     * @return The digits.
     */
    DigitCount getDigits();

    /**
     * <code>optional .OtpType type = 6;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>optional .OtpType type = 6;</code>
     * @return The type.
     */
    OtpType getType();

    /**
     * <code>optional int64 counter = 7;</code>
     * @return Whether the counter field is set.
     */
    boolean hasCounter();
    /**
     * <code>optional int64 counter = 7;</code>
     * @return The counter.
     */
    long getCounter();
  }
  /**
   * Protobuf type {@code OtpParameters}
   */
  public static final class OtpParameters extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:OtpParameters)
      OtpParametersOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 30,
        /* patch= */ 2,
        /* suffix= */ "",
        OtpParameters.class.getName());
    }
    // Use OtpParameters.newBuilder() to construct.
    private OtpParameters(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private OtpParameters() {
      secret_ = com.google.protobuf.ByteString.EMPTY;
      name_ = "";
      issuer_ = "";
      algorithm_ = 0;
      digits_ = 0;
      type_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OtpMigration.internal_static_OtpParameters_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OtpMigration.internal_static_OtpParameters_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OtpParameters.class, Builder.class);
    }

    private int bitField0_;
    public static final int SECRET_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString secret_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes secret = 1;</code>
     * @return Whether the secret field is set.
     */
    @Override
    public boolean hasSecret() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes secret = 1;</code>
     * @return The secret.
     */
    @Override
    public com.google.protobuf.ByteString getSecret() {
      return secret_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object name_ = "";
    /**
     * <code>optional string name = 2;</code>
     * @return Whether the name field is set.
     */
    @Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string name = 2;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISSUER_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile Object issuer_ = "";
    /**
     * <code>optional string issuer = 3;</code>
     * @return Whether the issuer field is set.
     */
    @Override
    public boolean hasIssuer() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string issuer = 3;</code>
     * @return The issuer.
     */
    @Override
    public String getIssuer() {
      Object ref = issuer_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          issuer_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string issuer = 3;</code>
     * @return The bytes for issuer.
     */
    @Override
    public com.google.protobuf.ByteString
        getIssuerBytes() {
      Object ref = issuer_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        issuer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ALGORITHM_FIELD_NUMBER = 4;
    private int algorithm_ = 0;
    /**
     * <code>optional .Algorithm algorithm = 4;</code>
     * @return Whether the algorithm field is set.
     */
    @Override public boolean hasAlgorithm() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .Algorithm algorithm = 4;</code>
     * @return The algorithm.
     */
    @Override public Algorithm getAlgorithm() {
      Algorithm result = Algorithm.forNumber(algorithm_);
      return result == null ? Algorithm.ALGORITHM_TYPE_UNSPECIFIED : result;
    }

    public static final int DIGITS_FIELD_NUMBER = 5;
    private int digits_ = 0;
    /**
     * <code>optional .DigitCount digits = 5;</code>
     * @return Whether the digits field is set.
     */
    @Override public boolean hasDigits() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .DigitCount digits = 5;</code>
     * @return The digits.
     */
    @Override public DigitCount getDigits() {
      DigitCount result = DigitCount.forNumber(digits_);
      return result == null ? DigitCount.DIGIT_COUNT_UNSPECIFIED : result;
    }

    public static final int TYPE_FIELD_NUMBER = 6;
    private int type_ = 0;
    /**
     * <code>optional .OtpType type = 6;</code>
     * @return Whether the type field is set.
     */
    @Override public boolean hasType() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional .OtpType type = 6;</code>
     * @return The type.
     */
    @Override public OtpType getType() {
      OtpType result = OtpType.forNumber(type_);
      return result == null ? OtpType.OTP_TYPE_UNSPECIFIED : result;
    }

    public static final int COUNTER_FIELD_NUMBER = 7;
    private long counter_ = 0L;
    /**
     * <code>optional int64 counter = 7;</code>
     * @return Whether the counter field is set.
     */
    @Override
    public boolean hasCounter() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional int64 counter = 7;</code>
     * @return The counter.
     */
    @Override
    public long getCounter() {
      return counter_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(1, secret_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, issuer_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeEnum(4, algorithm_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeEnum(5, digits_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeEnum(6, type_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeInt64(7, counter_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, secret_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, issuer_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, algorithm_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, digits_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, type_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, counter_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof OtpParameters)) {
        return super.equals(obj);
      }
      OtpParameters other = (OtpParameters) obj;

      if (hasSecret() != other.hasSecret()) return false;
      if (hasSecret()) {
        if (!getSecret()
            .equals(other.getSecret())) return false;
      }
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasIssuer() != other.hasIssuer()) return false;
      if (hasIssuer()) {
        if (!getIssuer()
            .equals(other.getIssuer())) return false;
      }
      if (hasAlgorithm() != other.hasAlgorithm()) return false;
      if (hasAlgorithm()) {
        if (algorithm_ != other.algorithm_) return false;
      }
      if (hasDigits() != other.hasDigits()) return false;
      if (hasDigits()) {
        if (digits_ != other.digits_) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (type_ != other.type_) return false;
      }
      if (hasCounter() != other.hasCounter()) return false;
      if (hasCounter()) {
        if (getCounter()
            != other.getCounter()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSecret()) {
        hash = (37 * hash) + SECRET_FIELD_NUMBER;
        hash = (53 * hash) + getSecret().hashCode();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasIssuer()) {
        hash = (37 * hash) + ISSUER_FIELD_NUMBER;
        hash = (53 * hash) + getIssuer().hashCode();
      }
      if (hasAlgorithm()) {
        hash = (37 * hash) + ALGORITHM_FIELD_NUMBER;
        hash = (53 * hash) + algorithm_;
      }
      if (hasDigits()) {
        hash = (37 * hash) + DIGITS_FIELD_NUMBER;
        hash = (53 * hash) + digits_;
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasCounter()) {
        hash = (37 * hash) + COUNTER_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getCounter());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OtpParameters parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OtpParameters parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OtpParameters parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OtpParameters parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OtpParameters parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OtpParameters parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OtpParameters parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static OtpParameters parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static OtpParameters parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static OtpParameters parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static OtpParameters parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static OtpParameters parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(OtpParameters prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OtpParameters}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OtpParameters)
        OtpParametersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return OtpMigration.internal_static_OtpParameters_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OtpMigration.internal_static_OtpParameters_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OtpParameters.class, Builder.class);
      }

      // Construct using OtpMigration.OtpParameters.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        secret_ = com.google.protobuf.ByteString.EMPTY;
        name_ = "";
        issuer_ = "";
        algorithm_ = 0;
        digits_ = 0;
        type_ = 0;
        counter_ = 0L;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return OtpMigration.internal_static_OtpParameters_descriptor;
      }

      @Override
      public OtpParameters getDefaultInstanceForType() {
        return OtpParameters.getDefaultInstance();
      }

      @Override
      public OtpParameters build() {
        OtpParameters result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public OtpParameters buildPartial() {
        OtpParameters result = new OtpParameters(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(OtpParameters result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.secret_ = secret_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.issuer_ = issuer_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.algorithm_ = algorithm_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.digits_ = digits_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.type_ = type_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.counter_ = counter_;
          to_bitField0_ |= 0x00000040;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OtpParameters) {
          return mergeFrom((OtpParameters)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OtpParameters other) {
        if (other == OtpParameters.getDefaultInstance()) return this;
        if (other.hasSecret()) {
          setSecret(other.getSecret());
        }
        if (other.hasName()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasIssuer()) {
          issuer_ = other.issuer_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasAlgorithm()) {
          setAlgorithm(other.getAlgorithm());
        }
        if (other.hasDigits()) {
          setDigits(other.getDigits());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasCounter()) {
          setCounter(other.getCounter());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                secret_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                name_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                issuer_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                int tmpRaw = input.readEnum();
                Algorithm tmpValue =
                    Algorithm.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(4, tmpRaw);
                } else {
                  algorithm_ = tmpRaw;
                  bitField0_ |= 0x00000008;
                }
                break;
              } // case 32
              case 40: {
                int tmpRaw = input.readEnum();
                DigitCount tmpValue =
                    DigitCount.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(5, tmpRaw);
                } else {
                  digits_ = tmpRaw;
                  bitField0_ |= 0x00000010;
                }
                break;
              } // case 40
              case 48: {
                int tmpRaw = input.readEnum();
                OtpType tmpValue =
                    OtpType.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(6, tmpRaw);
                } else {
                  type_ = tmpRaw;
                  bitField0_ |= 0x00000020;
                }
                break;
              } // case 48
              case 56: {
                counter_ = input.readInt64();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString secret_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes secret = 1;</code>
       * @return Whether the secret field is set.
       */
      @Override
      public boolean hasSecret() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bytes secret = 1;</code>
       * @return The secret.
       */
      @Override
      public com.google.protobuf.ByteString getSecret() {
        return secret_;
      }
      /**
       * <code>optional bytes secret = 1;</code>
       * @param value The secret to set.
       * @return This builder for chaining.
       */
      public Builder setSecret(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        secret_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes secret = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecret() {
        bitField0_ = (bitField0_ & ~0x00000001);
        secret_ = getDefaultInstance().getSecret();
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string name = 2;</code>
       * @return The name.
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private Object issuer_ = "";
      /**
       * <code>optional string issuer = 3;</code>
       * @return Whether the issuer field is set.
       */
      public boolean hasIssuer() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string issuer = 3;</code>
       * @return The issuer.
       */
      public String getIssuer() {
        Object ref = issuer_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            issuer_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string issuer = 3;</code>
       * @return The bytes for issuer.
       */
      public com.google.protobuf.ByteString
          getIssuerBytes() {
        Object ref = issuer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          issuer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string issuer = 3;</code>
       * @param value The issuer to set.
       * @return This builder for chaining.
       */
      public Builder setIssuer(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        issuer_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string issuer = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIssuer() {
        issuer_ = getDefaultInstance().getIssuer();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string issuer = 3;</code>
       * @param value The bytes for issuer to set.
       * @return This builder for chaining.
       */
      public Builder setIssuerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        issuer_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int algorithm_ = 0;
      /**
       * <code>optional .Algorithm algorithm = 4;</code>
       * @return Whether the algorithm field is set.
       */
      @Override public boolean hasAlgorithm() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional .Algorithm algorithm = 4;</code>
       * @return The algorithm.
       */
      @Override
      public Algorithm getAlgorithm() {
        Algorithm result = Algorithm.forNumber(algorithm_);
        return result == null ? Algorithm.ALGORITHM_TYPE_UNSPECIFIED : result;
      }
      /**
       * <code>optional .Algorithm algorithm = 4;</code>
       * @param value The algorithm to set.
       * @return This builder for chaining.
       */
      public Builder setAlgorithm(Algorithm value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        algorithm_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .Algorithm algorithm = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAlgorithm() {
        bitField0_ = (bitField0_ & ~0x00000008);
        algorithm_ = 0;
        onChanged();
        return this;
      }

      private int digits_ = 0;
      /**
       * <code>optional .DigitCount digits = 5;</code>
       * @return Whether the digits field is set.
       */
      @Override public boolean hasDigits() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional .DigitCount digits = 5;</code>
       * @return The digits.
       */
      @Override
      public DigitCount getDigits() {
        DigitCount result = DigitCount.forNumber(digits_);
        return result == null ? DigitCount.DIGIT_COUNT_UNSPECIFIED : result;
      }
      /**
       * <code>optional .DigitCount digits = 5;</code>
       * @param value The digits to set.
       * @return This builder for chaining.
       */
      public Builder setDigits(DigitCount value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        digits_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .DigitCount digits = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDigits() {
        bitField0_ = (bitField0_ & ~0x00000010);
        digits_ = 0;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .OtpType type = 6;</code>
       * @return Whether the type field is set.
       */
      @Override public boolean hasType() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional .OtpType type = 6;</code>
       * @return The type.
       */
      @Override
      public OtpType getType() {
        OtpType result = OtpType.forNumber(type_);
        return result == null ? OtpType.OTP_TYPE_UNSPECIFIED : result;
      }
      /**
       * <code>optional .OtpType type = 6;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(OtpType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .OtpType type = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        type_ = 0;
        onChanged();
        return this;
      }

      private long counter_ ;
      /**
       * <code>optional int64 counter = 7;</code>
       * @return Whether the counter field is set.
       */
      @Override
      public boolean hasCounter() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional int64 counter = 7;</code>
       * @return The counter.
       */
      @Override
      public long getCounter() {
        return counter_;
      }
      /**
       * <code>optional int64 counter = 7;</code>
       * @param value The counter to set.
       * @return This builder for chaining.
       */
      public Builder setCounter(long value) {

        counter_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 counter = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearCounter() {
        bitField0_ = (bitField0_ & ~0x00000040);
        counter_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:OtpParameters)
    }

    // @@protoc_insertion_point(class_scope:OtpParameters)
    private static final OtpParameters DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OtpParameters();
    }

    public static OtpParameters getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OtpParameters>
        PARSER = new com.google.protobuf.AbstractParser<OtpParameters>() {
      @Override
      public OtpParameters parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<OtpParameters> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<OtpParameters> getParserForType() {
      return PARSER;
    }

    @Override
    public OtpParameters getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MigrationPayload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MigrationPayload_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OtpParameters_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OtpParameters_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022OtpMigration.proto\"\206\001\n\020MigrationPayloa" +
      "d\022&\n\016otp_parameters\030\001 \003(\0132\016.OtpParameter" +
      "s\022\017\n\007version\030\002 \001(\005\022\022\n\nbatch_size\030\003 \001(\005\022\023" +
      "\n\013batch_index\030\004 \001(\005\022\020\n\010batch_id\030\005 \001(\005\"\242\001" +
      "\n\rOtpParameters\022\016\n\006secret\030\001 \001(\014\022\014\n\004name\030" +
      "\002 \001(\t\022\016\n\006issuer\030\003 \001(\t\022\035\n\talgorithm\030\004 \001(\016" +
      "2\n.Algorithm\022\033\n\006digits\030\005 \001(\0162\013.DigitCoun" +
      "t\022\026\n\004type\030\006 \001(\0162\010.OtpType\022\017\n\007counter\030\007 \001" +
      "(\003*V\n\tAlgorithm\022\036\n\032ALGORITHM_TYPE_UNSPEC" +
      "IFIED\020\000\022\010\n\004SHA1\020\001\022\n\n\006SHA256\020\002\022\n\n\006SHA512\020" +
      "\003\022\007\n\003MD5\020\004*=\n\nDigitCount\022\033\n\027DIGIT_COUNT_" +
      "UNSPECIFIED\020\000\022\007\n\003SIX\020\001\022\t\n\005EIGHT\020\002*7\n\007Otp" +
      "Type\022\030\n\024OTP_TYPE_UNSPECIFIED\020\000\022\010\n\004HOTP\020\001" +
      "\022\010\n\004TOTP\020\002"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MigrationPayload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MigrationPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MigrationPayload_descriptor,
        new String[] { "OtpParameters", "Version", "BatchSize", "BatchIndex", "BatchId", });
    internal_static_OtpParameters_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OtpParameters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_OtpParameters_descriptor,
        new String[] { "Secret", "Name", "Issuer", "Algorithm", "Digits", "Type", "Counter", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
